### PR TITLE
(WIP) Turn sidebar menu into Bottom Navigation on mobile

### PR DESCRIPTION
**Pull request by loxator**

### CODE REVIEW

**Comment by m3h0w** [comment]
Alternatively, for the time travel on mobile - we can consider hiding the element altogether, given that on my phone the data processing takes so long that the time travel is super slow anyway.

**Comment by loxator** [comment]
image

@mehow, this is how it looks after addressing some of your comments. I couldn't understand what you meant by point 3 about the Graphs. Please review the PR again and thanks for the constructive feed in the previous round of review!

**Comment by mehow** [comment]
Wrong @m3h0w .

**Comment by loxator** [comment]
@mehow Sorry!

**Pull request merged**
